//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _GuzellikSirlari.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CiltSagligi
    {
        public int CiltSagligiId { get; set; }
        public string CiltSagligiAdi { get; set; }
        public string CiltSagligiAciklama { get; set; }
    }
}
